# Use the official Nginx image as the base image
FROM nginx:latest

# Copy a custom Nginx configuration file (optional)
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the default Nginx port
EXPOSE 80

