services:
  nginx:
    build:
      context: .
    ports:
      - "8080:80" # Map port 8080 on your machine to port 80 in the container
    volumes:
      - ./content:/usr/share/nginx/html:ro # Bind the local content/ folder to the container's web root

